export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE";
export const DELETE_FLASH_MESSAGE = "DELETE_FLASH_MESSAGE";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_PROFILE_DESCRIPTION = "SET_PROFILE_DESCRIPTION";
export const SET_SKILLS = "SET_SKILLS";